version: "3"
services:
  app:
    build: .
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      HOST_MONGODB: mongo
    ports:
      - 8080:8080
    command: npm run dev

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: awp-api
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

      
volumes:
  mongodb: